const { init } = require('../src/db/init');

const items = [
  "T4_MAIN_SWORD","T5_MAIN_SWORD","T6_MAIN_SWORD","T7_MAIN_SWORD","T8_MAIN_SWORD",
  "T4_2H_DUALSWORD","T5_2H_DUALSWORD","T6_2H_DUALSWORD","T7_2H_DUALSWORD",
  "T4_MAIN_AXE","T5_MAIN_AXE","T6_MAIN_AXE","T7_MAIN_AXE","T8_MAIN_AXE",
  "T4_2H_AXE","T5_2H_AXE","T6_2H_AXE","T7_2H_AXE",
  "T4_MAIN_MACE","T5_MAIN_MACE","T6_MAIN_MACE","T7_MAIN_MACE","T8_MAIN_MACE",
  "T4_2H_MACE","T5_2H_MACE","T6_2H_MACE",
  "T4_MAIN_SPEAR","T5_MAIN_SPEAR","T6_MAIN_SPEAR","T7_MAIN_SPEAR","T8_MAIN_SPEAR",
  "T4_2H_SPEAR","T5_2H_SPEAR","T6_2H_SPEAR",
  "T4_MAIN_ROCK","T5_MAIN_ROCK","T6_MAIN_ROCK","T7_MAIN_ROCK","T8_MAIN_ROCK",
  "T4_2H_ROCK","T5_2H_ROCK",
  "T4_MAIN_HAMMER","T5_MAIN_HAMMER","T6_MAIN_HAMMER","T7_MAIN_HAMMER","T8_MAIN_HAMMER",
  "T4_2H_HAMMER","T5_2H_HAMMER","T6_2H_HAMMER",
  "T4_MAIN_BOW","T5_MAIN_BOW","T6_MAIN_BOW","T7_MAIN_BOW","T8_MAIN_BOW",
  "T4_2H_BOW","T5_2H_BOW",
  "T4_MAIN_CROSSBOW","T5_MAIN_CROSSBOW","T6_MAIN_CROSSBOW","T7_MAIN_CROSSBOW","T8_MAIN_CROSSBOW",
  "T4_2H_CROSSBOW","T5_2H_CROSSBOW","T6_2H_CROSSBOW",
  "T4_MAIN_DAGGER","T5_MAIN_DAGGER","T6_MAIN_DAGGER","T7_MAIN_DAGGER","T8_MAIN_DAGGER",
  "T4_2H_DAGGER","T5_2H_DAGGER","T6_2H_DAGGER",
  "T4_MAIN_FIRESTAFF","T5_MAIN_FIRESTAFF","T6_MAIN_FIRESTAFF","T7_MAIN_FIRESTAFF","T8_MAIN_FIRESTAFF",
  "T4_2H_FIRESTAFF","T5_2H_FIRESTAFF","T6_2H_FIRESTAFF","T7_2H_FIRESTAFF",
  "T4_MAIN_FROSTSTAFF","T5_MAIN_FROSTSTAFF","T6_MAIN_FROSTSTAFF","T7_MAIN_FROSTSTAFF","T8_MAIN_FROSTSTAFF",
  "T4_2H_FROSTSTAFF","T5_2H_FROSTSTAFF","T6_2H_FROSTSTAFF",
  "T4_MAIN_ARCANESTAFF","T5_MAIN_ARCANESTAFF","T6_MAIN_ARCANESTAFF","T7_MAIN_ARCANESTAFF","T8_MAIN_ARCANESTAFF",
  "T4_2H_ARCANESTAFF","T5_2H_ARCANESTAFF",
  "T4_MAIN_HOLYSTAFF","T5_MAIN_HOLYSTAFF","T6_MAIN_HOLYSTAFF","T7_MAIN_HOLYSTAFF","T8_MAIN_HOLYSTAFF",
  "T4_2H_HOLYSTAFF","T5_2H_HOLYSTAFF","T6_2H_HOLYSTAFF","T7_2H_HOLYSTAFF",
  "T4_MAIN_CURSEDSTAFF","T5_MAIN_CURSEDSTAFF","T6_MAIN_CURSEDSTAFF","T7_MAIN_CURSEDSTAFF","T8_MAIN_CURSEDSTAFF",
  "T4_2H_CURSEDSTAFF","T5_2H_CURSEDSTAFF","T6_2H_CURSEDSTAFF",
  "T4_MAIN_NATURESTAFF","T5_MAIN_NATURESTAFF","T6_MAIN_NATURESTAFF","T7_MAIN_NATURESTAFF","T8_MAIN_NATURESTAFF",
  "T4_2H_NATURESTAFF","T5_2H_NATURESTAFF","T6_2H_NATURESTAFF",
  "T4_HEAD_PLATE","T5_HEAD_PLATE","T6_HEAD_PLATE","T7_HEAD_PLATE","T8_HEAD_PLATE",
  "T4_ARMOR_PLATE","T5_ARMOR_PLATE","T6_ARMOR_PLATE","T7_ARMOR_PLATE","T8_ARMOR_PLATE",
  "T4_SHOES_PLATE","T5_SHOES_PLATE","T6_SHOES_PLATE","T7_SHOES_PLATE","T8_SHOES_PLATE",
  "T4_HEAD_LEATHER","T5_HEAD_LEATHER","T6_HEAD_LEATHER","T7_HEAD_LEATHER","T8_HEAD_LEATHER",
  "T4_ARMOR_LEATHER","T5_ARMOR_LEATHER","T6_ARMOR_LEATHER","T7_ARMOR_LEATHER","T8_ARMOR_LEATHER",
  "T4_SHOES_LEATHER","T5_SHOES_LEATHER","T6_SHOES_LEATHER","T7_SHOES_LEATHER","T8_SHOES_LEATHER",
  "T4_HEAD_CLOTH","T5_HEAD_CLOTH","T6_HEAD_CLOTH","T7_HEAD_CLOTH","T8_HEAD_CLOTH",
  "T4_ARMOR_CLOTH","T5_ARMOR_CLOTH","T6_ARMOR_CLOTH","T7_ARMOR_CLOTH","T8_ARMOR_CLOTH",
  "T4_SHOES_CLOTH","T5_SHOES_CLOTH","T6_SHOES_CLOTH","T7_SHOES_CLOTH","T8_SHOES_CLOTH",
  "T4_BAG","T5_BAG","T6_BAG","T7_BAG","T8_BAG",
  "T4_OFF_SHIELD","T5_OFF_SHIELD","T6_OFF_SHIELD","T7_OFF_SHIELD",
  "T4_CAPE","T5_CAPE","T6_CAPE","T7_CAPE","T8_CAPE",
  "T4_MAIN_TORCH","T5_MAIN_TORCH","T6_MAIN_TORCH",
  "T4_MAIN_BOOK","T5_MAIN_BOOK","T6_MAIN_BOOK",
  "T4_POTION_HEAL","T5_POTION_HEAL","T6_POTION_HEAL","T7_POTION_HEAL","T8_POTION_HEAL",
  "T4_POTION_ENERGY","T5_POTION_ENERGY","T6_POTION_ENERGY",
  "T4_ORE","T5_ORE","T6_ORE","T7_ORE","T8_ORE",
  "T4_WOOD","T5_WOOD","T6_WOOD","T7_WOOD","T8_WOOD",
  "T4_FIBER","T5_FIBER","T6_FIBER","T7_FIBER","T8_FIBER",
  "T4_HIDE","T5_HIDE","T6_HIDE","T7_HIDE","T8_HIDE",
  "T4_METALBAR","T5_METALBAR","T6_METALBAR","T7_METALBAR","T8_METALBAR",
  "T4_PLANK","T5_PLANK","T6_PLANK","T7_PLANK","T8_PLANK",
  "T4_CLOTH","T5_CLOTH","T6_CLOTH","T7_CLOTH","T8_CLOTH",
  "T4_LEATHER","T5_LEATHER","T6_LEATHER","T7_LEATHER","T8_LEATHER",
];

const db = init();
const stmt = db.prepare('INSERT OR IGNORE INTO public_sync_watchlist (item_unique_name) VALUES (?)');
const tx = db.transaction((ids) => {
  let added = 0;
  for (const id of ids) {
    const r = stmt.run(id);
    if (r.changes) added++;
  }
  return added;
});

const added = tx(items);
console.log(`[populate-watchlist] ${added} itens adicionados, ${items.length - added} já existiam`);
const total = db.prepare('SELECT COUNT(*) as c FROM public_sync_watchlist').get().c;
console.log(`[populate-watchlist] total na watchlist: ${total}`);
